name: Backend CI (Laravel)

on:
  push:
    paths: ['taskcurso/**', '.github/workflows/backend-ci.yml']
  pull_request:
    paths: ['taskcurso/**', '.github/workflows/backend-ci.yml']
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: sol_store_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres -d sol_store_test"
          --health-interval=5s --health-timeout=5s --health-retries=10

    defaults:
      run:
        working-directory: taskcurso

    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, xml, bcmath, intl, gd, pdo_pgsql
          coverage: none

      - uses: actions/cache@v4
        with:
          path: |
            ~/.composer/cache/files
            taskcurso/vendor
          key: composer-${{ runner.os }}-${{ hashFiles('taskcurso/composer.lock') }}
          restore-keys: |
            composer-${{ runner.os }}-

      - name: Install Composer deps
        run: composer install --no-interaction --prefer-dist --no-progress -o

      - name: Prepare .env.testing
        run: |
          cp .env.example .env || true
          cp .env .env.testing || true
          sed -i 's/^APP_ENV=.*/APP_ENV=testing/' .env.testing
          sed -i 's/^DB_CONNECTION=.*/DB_CONNECTION=pgsql/' .env.testing
          sed -i 's/^DB_HOST=.*/DB_HOST=127.0.0.1/' .env.testing
          sed -i 's/^DB_PORT=.*/DB_PORT=5432/' .env.testing
          sed -i 's/^DB_DATABASE=.*/DB_DATABASE=sol_store_test/' .env.testing
          sed -i 's/^DB_USERNAME=.*/DB_USERNAME=postgres/' .env.testing
          sed -i 's/^DB_PASSWORD=.*/DB_PASSWORD=postgres/' .env.testing

      - name: App key + JWT secret
        run: |
          php artisan key:generate --env=testing --force
          php artisan jwt:secret -n --force || true

      - name: Migrate + seed
        run: php artisan migrate:fresh --seed --env=testing

      - name: Run tests
        run: php artisan test --env=testing