name: CI - Backend (completo)
on:
  push:
    branches-ignore: [ "develop", "production" ]
  pull_request:

jobs:
  backend-tests-full:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Levantar servicios backend y DB
        run: docker compose up -d database backend

      - name: Migrar y seedar entorno testing
        run: docker compose exec -T backend sh -lc "php artisan migrate:fresh --seed --env=testing"

      - name: Correr toda la suite de pruebas
        run: docker compose exec -T backend sh -lc "php artisan test --env=testing"

      - name: Logs si algo falla
        if: failure()
        run: docker compose logs --tail=200
