name: CI - Backend (deploy branches, attach-only)
on:
  push:
    branches: [ "develop", "production" ]

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Prepare .env.testing (best-effort)
        run: |
          docker compose exec -T backend bash -lc '
            [ -f taskcurso/.env.testing ] || cp taskcurso/.env.testing.example taskcurso/.env.testing
            php artisan key:generate --env=testing --force || true
            php artisan jwt:secret   --env=testing --force || true
          ' || true

      - name: Run tests (attach-only)
        run: docker compose exec -T backend sh -lc "php artisan test --env=testing"
