name: CI - Backend (completo)
on:
  push:
    branches-ignore: [ "develop", "production" ]
  pull_request:

jobs:
  backend-tests-full:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Levantar servicios backend y DB
        run: docker compose up -d database backend

      - name: Wait for backend to be ready
        run: sleep 10

      - name: Check disk space
        run: df -h

      - name: Install unzip in container
        run: docker compose exec -T backend apt-get update && docker compose exec -T backend apt-get install -y unzip

      - name: Fix permissions in container
        run: docker compose exec -T backend chown -R www-data:www-data /var/www/html

      - name: Clear Composer cache
        run: docker compose exec -T backend composer clear-cache

      - name: Install Composer dependencies
        env:
          COMPOSER_MEMORY_LIMIT: -1
        run: |
          docker compose exec -T backend bash -c "COMPOSER_MEMORY_LIMIT=-1 composer install \
            --no-interaction \
            --prefer-dist \
            --optimize-autoloader \
            --no-scripts"

      - name: Migrar y seedar entorno testing
        run: docker compose exec -T backend sh -lc "php artisan migrate:fresh --seed --env=testing"

      - name: Correr toda la suite de pruebas
        run: docker compose exec -T backend sh -lc "php artisan test --env=testing"

      - name: Logs si algo falla
        if: failure()
        run: docker compose logs --tail=200
