name: Deploy to Staging
on:
  push:
    branches: [ "develop" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: actions/checkout@v4

      - name: Cargar llave SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Agregar host a known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.GCP_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy STAGING (mínimo para probar)
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.GCP_HOST }} 'bash -lc "
            set -e
            echo OK-SSH
            cd ~/sol-store-ecommerce
            git pull origin develop || true
            docker compose down
            docker compose up -d --build
            docker compose ps
          "'

