name: Deploy to Production
on:
  push:
    branches: [ "production" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production   # si configuraste Required reviewers, pedirá aprobación

    steps:
      - uses: actions/checkout@v4

      - name: Load SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: (Optional) known_hosts
        if: ${{ secrets.KNOWN_HOSTS != '' }}
        #run: |
        #  mkdir -p ~/.ssh
        #  echo "${{ secrets.KNOWN_HOSTS }}" >> ~/.ssh/known_hosts

      - name: Deploy on PRODUCTION
        run: |
          ssh -i ${{ secrets.SSH_PRIVATE_KEY }} ${{ secrets.SSH_USER }}@${{ secrets.GCP_HOST }} bash -lc '
            set -e

            cd ~/sol-store-ecommerce

            # update code from production branch
            git pull origin production

            # run containers 
            docker compose down
            docker compose up -d --build
          '
