# .github/workflows/frontend-ci.yml
name: Frontend CI (Vitest)

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: front-vue
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Con lockfile -> usa cache
      - name: Setup Node (with cache)
        if: ${{ hashFiles('front-vue/package-lock.json') != '' }}
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: front-vue/package-lock.json

      # Sin lockfile -> sin cache
      - name: Setup Node (no cache)
        if: ${{ hashFiles('front-vue/package-lock.json') == '' }}
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: |
          if [ -f package-lock.json ]; then npm ci; else npm install; fi

      - name: Run Vitest
        run: npm run test -- --run
