name: CI - Frontend (Vue)
on:
  push:
  pull_request:

jobs:
  test-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: front-vue
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: front-vue/package-lock.json

      - name: Install deps
        #run: npm ci

      - name: ESLint
        #run: npm run lint --if-present

      - name: Unit tests (Vitest)
        #run: npm run test --if-present

      - name: Build
        #run: npm run build

      - name: Upload build (opcional)
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: front-vue/dist
